### PR TITLE
Reverts baked-in NstDatabase.xml

### LINKED ISSUE #5: [3DS] Occasional crash on ROM load
When loading a ROM on the 3DS, the core will usually crash with an ARM11 exception. It looks like this is related to loading NstDatabase: it fails with https://github.com/libretro/nestopia/commit/354fa2f0f3bb9884988b05a6bc0e60dae961bec4, and earlier commits will fail in the same way if NstDatabase.xml is in the system directory.

Here's the dump:
```
Processor: ARM11 (core 0)
Exception type: prefetch abort (kernel panic)
Fault status: Debug event
Current process: 3dsx_app (0004001000021100)

Register dump:

r0             00000000            r1             00000000
r2             e6a83000            r3             00000000
r4             00000000            r5             ff539d88
r6             00000000            r7             00000001
r8             e6a81000            r9             08800000
r10            00000100            r11            fff2f2b4
r12            ee147460            sp             ff539d18
lr             fff1c76c            pc             fff1c7c0

cpsr           60000113            dfsr           000008ff
ifsr           00000002            far            7affffee
fpexc          40000700            fpinst         eefd7bc7
fpinst2        eefd7bc7

Code dump:

fff1c794:       e12fff1e        bx      lr
fff1c798:       e3510000        cmp     r1, #0, 0
fff1c79c:       0a000005        beq     0xfff1c7b8
fff1c7a0:       e1902f9f        ldrex   r2, [r0]
fff1c7a4:       e5812000        str     r2, [r1]
fff1c7a8:       e180cf91        strex   r12, r1, [r0]
fff1c7ac:       e35c0000        cmp     r12, #0, 0
fff1c7b0:       1afffffa        bne     0xfff1c7a0
fff1c7b4:       e12fff1e        bx      lr
fff1c7b8:       e320f000        nop     {0}
fff1c7bc:       e1a00000        nop                     ; (mov r0, r0)
fff1c7c0:       e12fff7e        bkpt    0xfffe


Stack dump:

ff539d18:  00 00 00 00 1c a5 f1 ff  00 00 00 00 00 80 81 08   |................|
ff539d28:  5c bb f7 ff 51 00 00 00  00 74 14 ee 38 4d f2 ff   |\...Q....t..8M..|
ff539d38:  00 10 a8 26 00 10 00 00  00 00 10 00 87 00 00 00   |...&............|
ff539d48:  24 e2 13 ee 64 74 14 ee  c0 9d 53 ff 5c bb f7 ff   |$...dt....S.\...|
ff539d58:  00 50 57 08 f4 02 00 00  88 9d 53 ff 5c bb f7 ff   |.PW.......S.\...|
ff539d68:  f4 02 00 00 00 50 57 08  00 00 00 00 00 00 00 00   |.....PW.........|
ff539d78:  00 90 86 08 30 00 00 00  7c 9e 53 ff 44 00 f2 ff   |....0...|.S.D...|
ff539d88:  b0 01 00 00 e0 8f f9 ff  1c ea f9 ff 5c bb f7 ff   |............\...|
ff539d98:  5c bb f7 ff f5 1b e0 e0  00 01 00 00 00 00 00 00   |\...............|
ff539da8:  00 00 00 00 00 90 86 08  30 00 00 00 24 d0 f1 ff   |........0...$...|
ff539db8:  1b 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539dc8:  00 80 86 08 00 80 39 07  5c bb f7 ff 2c 9e 53 ff   |......9.\...,.S.|
ff539dd8:  00 50 57 08 5c bb f7 ff  00 50 57 08 f4 02 00 00   |.PW.\....PW.....|
ff539de8:  00 00 00 00 00 90 86 08  00 50 57 08 f4 02 00 00   |.........PW.....|
ff539df8:  00 00 00 00 00 00 00 00  01 01 00 00 05 bb 00 00   |................|
ff539e08:  7c 9e 53 ff c0 0d f1 ff  00 00 00 00 00 00 00 00   ||.S.............|
ff539e18:  00 00 00 00 00 01 00 00  00 00 00 00 1b 00 00 00   |................|
ff539e28:  00 00 00 00 00 00 00 08  00 90 86 00 1b 00 00 00   |................|
ff539e38:  05 bb 00 00 5c bb f7 ff  7c 9e 53 ff 00 50 57 08   |....\...|.S..PW.|
ff539e48:  00 00 00 00 00 50 57 08  00 40 2f 00 00 00 00 00   |.....PW..@/.....|
ff539e58:  01 01 00 00 01 00 00 00  40 bb f7 ff 5c bb f7 ff   |........@...\...|
ff539e68:  00 90 86 08 bc 85 f0 ff  00 40 2f 00 01 01 00 00   |.........@/.....|
ff539e78:  03 00 00 00 00 00 00 00  00 90 ff ff e8 9e 53 ff   |..............S.|
ff539e88:  00 50 57 08 00 00 00 00  00 40 2f 00 03 00 00 00   |.PW......@/.....|
ff539e98:  94 82 f0 ff 00 a1 5e 00  ec a6 5e 00 f8 06 00 40   |......^...^....@|
ff539ea8:  01 00 00 00 01 00 00 00  00 00 00 00 c8 3b 00 40   |.............;.@|
ff539eb8:  01 00 00 00 03 00 00 00  00 00 00 00 00 40 2f 00   |.............@/.|
ff539ec8:  03 00 00 00 03 00 00 00  48 41 2f 00 00 a1 5e 00   |........HA/...^.|
ff539ed8:  ec a6 5e 00 0c 07 00 40  01 00 00 00 03 00 00 00   |..^....@........|
ff539ee8:  00 00 00 00 fc 00 00 40  01 00 00 00 00 50 57 08   |.......@.....PW.|
ff539ef8:  00 00 00 00 00 40 2f 00  03 00 00 00 48 41 2f 00   |.....@/.....HA/.|
ff539f08:  00 a1 5e 00 ec a6 5e 00  80 34 2f 00 00 00 00 00   |..^...^..4/.....|
ff539f18:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539f28:  00 ed ff 0f 44 0f 10 00  48 24 3f 00 10 00 07 a0   |....D...H$?.....|
ff539f38:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539f48:  00 01 00 01 00 00 00 00  c8 10 fd ff 13 01 00 60   |...............`|
ff539f58:  00 00 00 00 20 9d 53 ff  00 78 14 ee 00 00 70 08   |.... .S..x....p.|
ff539f68:  00 01 00 00 b4 f2 f2 ff  f8 9c 53 ff 70 dd f1 ff   |..........S.p...|
ff539f78:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539f88:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539f98:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539fa8:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539fb8:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539fc8:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539fd8:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539fe8:  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   |................|
ff539ff8:  00 07 00 40 00 00 c0 03                            |...@....|
```

I've attached the raw file, too.
[crash_dump_00000014.dmp.zip](https://github.com/libretro/nestopia/files/3705414/crash_dump_00000014.dmp.zip)

### LINKED ISSUE #19: load ROMs not in db
this is an annoying behavior Nestopia has compared to other emus like [fceumm](https://github.com/libretro/libretro-fceumm): if a ROM is missing in the `NstDatabase.xml` it won't load at all.

I know the correct way to "fix" this is by adding a new entry in the db, however this is still an annoying process to repeat everytime you want to try a new patch.

As alternative, [NES ROMs carry infos like the mapper inside the iNes header](https://bheisler.github.io/post/nes-rom-parser-with-nom/#the-ines-header), so maybe we can fallback to that if there is no match with the db?

### LINKED ISSUE #25: Don't bake the NstDatabase.xml file into the core
This is beyond stupid, and I just wasted _hours_ of my time trying to get Micro Mages added to the database so that a few of my friends and I could play 4 players over netplay.

**DO NOT DO THIS**, configuration files are meant to be configured. RetroArch warns that the file is missing, and the [docs][1] prompt you to download it yourself. This is incredibly misleading and infuriating. The decision to do this is incredibly misguided, since it assumes the set of NES games is fixed, which it definitely isn't as homebrew and commercial games are still developed.

[1]: https://docs.libretro.com/library/nestopia_ue/#nstdatabasexml

### PR DESCRIPTION
**Pull request by keithbowes**
With rdanbrook's blessing
Fixes #5
Fixes #19
Fixes #25

### CODE REVIEW

**Comment by inactive123** [comment]
I don't want this to be outright removed. I'd prefer if it remains baked-in, HOWEVER, IF some user wants to override it with a supplied config file like this, he can do so as well. I'm fine with that.

The vast majority of our userbase might never have this file supplied, so it's absolutely bad to remove this and I consider it a regression. As long as what I propose above can be achieved, then I'm fine with how things go, but outright removal of a baked-in NstDatabase.xml is something I completely oppose and will veto.

**Comment by keithbowes** [comment]
Ah, you said revert, so I just did a reverse patch of the commit that added it and resolved the conflicts.  I suppose I misunderstood.  I'll work on readding the baked-in support.

**Comment by keithbowes** [comment]
Well, none of the ROMs I have don't work without the database.  The region and controls can be configured in the UI, so really the only thing left is mappers.  I considered adding an option for mappers (like Gearboy does) when I added the configurable controls, but the quantity of mappers makes that extremely difficult with little benefit.  Maybe it could be added just for mappers known not to be detected correctly (if any).

**Comment by Ryunam** [comment]
If I may, could it be made a core option that defaults to using the baked-in database, unless the user specifies that they want to use an external file or no database at all? Something like:

"Use Baked-in NstDatabase.xml file" -> ON (Default); OFF (looks for the NstDatabase.xml file in the system folder and does not use the internal database at all)

The advantage of doing it this way is that it is possible to customize this to each user's preference. You can save a per-game core option file and micromanage this for the sake of having the best compatibility, while preserving the default approach as it is currently implemented.

**Comment by inactive123** [comment]
yeah I'd be fine with a core option like that, and to leave it enabled by default so it uses the baked NstDatabase.xml, and by changing the core option, it will look for a user supplied file instead.

**Comment by Ryunam** [comment]
I see that this PR has been closed for now. Is the possibility of a core option that allows users to enable/disable the baked-in Database still being considered?

**Comment by RokkumanX** [comment]
@Ryunam 

This pre-built core contains all Nestopia updates and this closed PR, Santa Claus is at it again!

[nestopia_libretro.zip](https://github.com/libretro/nestopia/files/6686629/nestopia_libretro.zip)

**Pull request closed without merging**
