### PR TITLE
Fix source of netplay desyncs

### PR DESCRIPTION
**Pull request by N7Alpha**
I accidently assassinated my [first PR](https://github.com/libretro/nestopia/pull/80#issuecomment-1925203613) when I rebased on the upstream branch. In any case the desyncs still happened when I tested. This commit doesn't really differ from my first implementation I just fixed conflicts. Most of the code that needed to change was more or less the same thankfully it just got moved around.

### CODE REVIEW

**Comment by carmiker** [comment]
Sorry, I had to revert this as it broke old states. I think we can work around this in a way that doesn't break old states, but I don't have time to do it immediately.

**Comment by N7Alpha** [comment]
> Sorry, I had to revert this as it broke old states. I think we can work around this in a way that doesn't break old states, but I don't have time to do it immediately.

I see yeah. I didn't even think about backwards compatibility, but it seems obvious now that you mention it. As long as you know about the issue and the root cause that's all that matters.

**Comment by carmiker** [comment]
I've taken your fix and allowed it to handle states that were created before the fix.

**Comment by N7Alpha** [comment]
> I've taken your fix and allowed it to handle states that were created before the fix.

Awesome cool I’ll give it a try later today

**Pull request merged**
