### PR TITLE
Bake NstDatabase.xml into the core

### PR DESCRIPTION
**Pull request by rdanbrook**
The .hpp file containing the hexdump is large. If this breaks compilation on some platforms, we can find another solution.

### CODE REVIEW

**Comment by paradadf** [comment]
@rdanbrook hi! does this mean, there is no need to have NstDatabase.xml in the system directory?

**Comment by rdanbrook** [comment]
That is correct.

**Comment by paradadf** [comment]
Thanks!

**Comment by keithbowes** [comment]
It would be interesting to know why this was specified in an XML file to begin with.  It means that Nestopia has to have its own XML parser (not using an already existing XML parser, like expat or libxml2) and then take the inefficient step of parsing a huge XML file (988 kilobytes; according to xmllint, containing 2901 entries) instead of having the overrides in the code itself.  Though, perhaps having such a huge source file, with 2901 conditions, would trip up compilers too.

This "baking in" really seems not to be very maintainable.  What happens if the XML file needs to be updated?  Will nstdatabase.hpp have to be manually updated given such a contingency?  (Not that baking it in was necessary anyway, as the libretro documentation already specifies that you need to place the NstDatabase.xml file in your system directory.)

**Comment by rdanbrook** [comment]
@keithbowes your guess is as good as mine. XML is a terrible format for a number of reasons. Perhaps the original author wanted to use XML because he felt like learning it at the time. Maybe he wanted it to be easy for people to add their own entries and load it after modifying it. I see no reason why the entries couldn't go in some kind of map or tree. That's not how the software was written in the early 2000s though, and the effort to change it is far more than the effort of doing a hexdump on the rare occasion that the XML database changes.

This was done to simplify life for the end user. Copying the XML database into your system directory is easier on some platforms than others. I dragged my feet on this issue for years, and at this point as I hand off maintenance of this emulator, I went with a solution that leads to less bug reports and easier operation for the majority of people.

**Pull request merged**
