### PR TITLE
Fully optional 2x overclocking for nestopia

### PR DESCRIPTION
**Pull request by meepingsnesroms**
I want the bounty to be put toward a j2me/midlet emulator since I feel taking it would be a conflict of interest.

If any bugs are found within the next month, I will fix them within a few days if possible.

### CODE REVIEW

**Comment by rdanbrook** [comment]
Will give it a try to test it out, give me some time though.

**Comment by retro-wertz** [comment]
just did quick test. this has affected sound and speed not in a good way. checkout Contra(J)

**Comment by rdanbrook** [comment]
It seems to not actually reduce lag either... I have only tested with Mega Man 3.

**Comment by retro-wertz** [comment]
thats interesting, if you Reset, the speed becomes normal, but i dont think its overclocking. Contra Force should be a good benchmark if its in oc or not as it has slowdowns even from the start of stage.

**Comment by meepingsnesroms** [comment]
In contra force overclocking slows down the music so something is broken, but the game does seem to run faster.

My tests where done with the 240pee test suite and the numbers dont change for ntsc but they double for pal.

But ntsc does stop toggling between .6 and .7 as often so I new it was doing something possibly running 2 frames.

**Comment by meepingsnesroms** [comment]
I fixed the reset issue, overclocking was being disabled on console reset when it should only be initialized to false on load then use whatever the option was set to last.

The music is likely slowing because the apu needs to be disabled after the last real scanline and be reenabled on the next frame.

**Comment by retro-wertz** [comment]
this is actually skipping frames(or a similar nature). Using Contra(J) again as an example, when player spawns he should be blinking, but here its either he is invisible(most of the time) or solid sprite instead. Another test is to use the turbo function. when shooting with turbo, 4 bullets are suppose to be distinctly seen shooting out, but i only see 2 bullets.

**Comment by meepingsnesroms** [comment]
How would I fix that?

What determines when the nes switches frames vs running a longer frame?

**Comment by rdanbrook** [comment]
When the NES switches frames depends on the PPU: http://wiki.nesdev.com/w/images/d/d1/Ntsc_timing.png

It never "runs a longer frame".

**Comment by meepingsnesroms** [comment]
That is how fceumm does overclocking, it adds extra invisible scanlines making a longer frame.

**Comment by rdanbrook** [comment]
Have you tried just changing the CPU/PPU ratio and yet still running the APU at normal speed? Say, 1 or 2 PPU cycles per CPU cycle.

**Comment by retro-wertz** [comment]
i am just reporting based on how the game "looks" like with the overclock, not the technicals behind it, but hey if its not a valid test, then ok.

**Comment by meepingsnesroms** [comment]
How can I change the cpu/ppu ratio?

I did not say it was an invalid test, I actually found the source of the bug(with the reset variable) because of what you said.

This is new to me, I have very little experience with the nes.

**Comment by meepingsnesroms** [comment]
Ok, I just moved overclocking to the cpu section instead of messing with the ppu and it is acting like fceumm does.

There may still be audio pops if dmc registers are written to during the extra cycles since there is no check, but the frame skipping is fixed and it actually overclocks now.

Please test, I tested with Contra Force(U), Contra(U) and 240pee and it works.

**Comment by Tatsuya79** [comment]
Not about this PR, but about the J2ME core note in the 1st post.
It seems someone is working on one already:
https://retropie.org.uk/forum/topic/11441/would-you-like-to-play-nokia-j2me-games-on-retropie/222

**Comment by rdanbrook** [comment]
It seems to work well with Mega Man 3 at this point, does not completely remove lag but does slightly improve the situation, and I hear no audio problems there.

I want to see more testing before I merge it though, and it would also make sense to clean up the commit history as well once it's all said and done.

Good work so far.

**Comment by meepingsnesroms** [comment]
I still want the bounty to go toward that, currently it is retropi only.
To get the bounty it needs to work on Linux(x86-32,x86-64,armv7), Android(x86-32,armv6,armv7), MacOS and iOS.

Windows, 3ds and vita support can come later.

**Comment by saftle** [comment]
In order to transfer the bounty, I can e-mail the support at bountysource.com and have it switched to a different issue. 

Since a j2me/midlet libretro project does not exist, should we perhaps create an issue elsewhere in an existing project (i.e. retroarch)?

**Comment by rdanbrook** [comment]
I am going to accept this pull request, but I will take the changes myself and commit them as one single commit, and also fix some of the whitespace issues that seemed to make their way in.

Thanks so much for making this happen, @meepingsnesroms .

**Comment by saftle** [comment]
Thank you @meepingsnesroms for your work on this. Can't wait to try it out!

**Comment by bparker06** [comment]
@saftle Just FYI There was a user on discord a few days ago named adolfobenjaminv that wanted to start a bounty for one.

**Comment by saftle** [comment]
@bparker06 thanks for the heads up. I'll try to reach out.

**Pull request closed without merging**
