### PR TITLE
Add Nescap & Unsaturated-v7 palettes.

### PR DESCRIPTION
**Pull request by Tatsuya79**

### CODE REVIEW

**Comment by rdanbrook** [comment]
What exactly is the "nescap" palette? I don't want to be in the business of hardcoding every palette out there into the libretro port, there is an option for custom palettes for that reason. On the other hand, the "unsaturated" palette is already in there so I welcome that change.

**Comment by Tatsuya79** [comment]
[You can read about it here.](http://rgbsource.blogspot.fr/search/label/NES%20Color%20Palette)
That's probably the most accurate one.
[Some discussion about Nescap vs Unsaturated here with their respective authors.](http://shmups.system11.org/viewtopic.php?f=6&t=56373&start=150)

**Comment by Tatsuya79** [comment]
If you don't want too many palettes, perhaps we could remove YUV-v3 as [it's been discontinued by its author in favour of Unsaturated](http://libretro.com/forums/showthread.php?t=5315&page=3&p=42171&viewfull=1#post42171).

**Comment by hizzlekizzle** [comment]
Yeah, I think replacing YUV-v3 is a fine course of action.

**Comment by rdanbrook** [comment]
Yeah, I'm in favour of removing YUV-v3.

**Comment by rdanbrook** [comment]
Would you also be willing to do the commits to remove the nescap palette? I'll add it to the /extras subdirectory after I merge this.

**Comment by rdanbrook** [comment]
Thanks for taking the time to make this happen.

**Pull request merged**
