### PR TITLE
Add fourscore support for various titles & support for some Morphcat games

### PR DESCRIPTION
**Pull request by BlazeEntertainment**
Added support for some Mega Cat titles but more specifically Morpchat titles:

- Micro Mages
- Micro Mages: Second Quest
- BOBL 1.2 (MMC1 version)

### CODE REVIEW

**Comment by rdanbrook** [comment]
https://github.com/libretro/nestopia/pull/54/files#diff-1806dd12d8850b2736a91a44764889598322a117699867db72bd2d20a6208425R27082
This was already present, otherwise the PR looks good.

**Comment by inactive123** [comment]
@rdanbrook Can it be merged as is?

**Comment by rdanbrook** [comment]
@twinaphex the best option is to close this one and merge #55. I just merged these changes, removed the duplicate entry, and updated the baked in database.

**Comment by inactive123** [comment]
#55 replaces this, closing.

**Pull request closed without merging**
